workspace = { }

[package]
name = "tauri-bundler"
version = "2.0.0-alpha.15"
authors = [
  "George Burton <burtonageo@gmail.com>",
  "Tauri Programme within The Commons Conservancy"
]
categories = [ "command-line-utilities", "development-tools::cargo-plugins" ]
license = "Apache-2.0 OR MIT"
keywords = [ "bundle", "cargo", "tauri" ]
repository = "https://github.com/tauri-apps/tauri"
description = "Wrap rust executables in OS-specific app bundles for Tauri"
edition = "2021"
rust-version = "1.70"
exclude = [ "CHANGELOG.md", "/target", "rustfmt.toml" ]

[dependencies]
tauri-utils = { version = "2.0.0-alpha.14", path = "../../core/tauri-utils", features = [ "resources" ] }
image = "0.24.7"
libflate = "2.0"
anyhow = "1.0"
thiserror = "1.0"
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
strsim = "0.10.0"
tar = "0.4.40"
walkdir = "2"
handlebars = "5.0"
tempfile = "3.8.1"
log = { version = "0.4.20", features = [ "kv_unstable" ] }
dirs-next = "2.0"
os_pipe = "1"
ureq = { version = "2.8", default-features = false, features = [ "socks-proxy" ] }
native-tls = { version = "0.2", optional = true }
hex = "0.4"
semver = "1"
sha1 = "0.10"
sha2 = "0.10"
zip = { version = "0.6", default-features = false, features = [ "deflate" ] }
dunce = "1"

[target."cfg(target_os = \"windows\")".dependencies]
uuid = { version = "1", features = [ "v4", "v5" ] }
bitness = "0.4"
winreg = "0.51"
glob = "0.3"

  [target."cfg(target_os = \"windows\")".dependencies.windows-sys]
  version = "0.48"
  features = [
  "Win32_System_SystemInformation",
  "Win32_System_Diagnostics_Debug"
]

[target."cfg(target_os = \"macos\")".dependencies]
icns = { package = "tauri-icns", version = "0.1" }
time = { version = "0.3", features = [ "formatting" ] }
plist = "1"

[target."cfg(any(target_os = \"macos\", target_os = \"windows\"))".dependencies]
regex = "1"

[target."cfg(target_os = \"linux\")".dependencies]
heck = "0.4"
ar = "0.9.0"
md5 = "0.7.0"
rpm = "0.13.1"

[lib]
name = "tauri_bundler"
path = "src/lib.rs"

[features]
default = [ "rustls" ]
native-tls = [ "ureq/native-tls" ]
native-tls-vendored = [ "native-tls", "native-tls/vendored" ]
rustls = [ "ureq/tls" ]
